services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: app-backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: app-frontend
    ports:
      - "3000:80"

  postgres:
    container_name: database
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: