services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8080:8080'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  postgres:
    container_name: database
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '5432:5432'

volumes:
  postgres_data: